APP_NAME=
APP_VERSION=

FILE_ALLOWED_TYPES=["text/plain","application/pdf"]
FILE_MAX_SIZE=10
FILE_DEFAULT_CHUNK_SIZE=512000 #512KB

POSTGRES_USERNAME=
POSTGRES_PASSWORD=
POSTGRES_HOST=
POSTGRES_PORT=
POSTGRES_MAIN_DATABASE=

# ====================== LLM Config =======================

GENERATION_BACKEND="OPENAI"
EMBEDDING_BACKEND="OPENAI"

OPENAI_API_KEY=

OPENAI_API_URL=
COHERE_API_KEY=

# GENERATION_MODEL_ID="command-a-03-2025"
# EMBEDING_MODEL_ID="embed-english-light-v3.0"
GENERATION_MODEL_ID=
EMBEDING_MODEL_ID=

EMBEDDING_MODEL_SIZE=1024


DEFAULT_INPUT_MAX_CHARACTERS=1024
DEFAULT_GENERATION_MAX_OUTPUT_TOKENS=200
DEFAULT_GENERATION_TEMPERATURE=0.1  

# ====================== VectorDB Config =======================
VECTOR_DB_BACKEND_LITERAL=[ "QDRANT", "PGVECTOR"]

VECTOR_DB_BACKEND="PGVECTOR"
VECTR_DB_PATH="qdrant_db"
VECTOR_DB_DISTANCE_METHOD="COSINE"

VECTOR_DB_PGVEC_INDEX_THRESHOLD=100 

# ====================== Templates Config =======================
DEFAULT_LANGUAGE="en"
